# -*- coding: utf-8 -*-
"""Logica de programação

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbj_GTk5MTF1Ty-C7QJxKdTIoSKM3b5t

# Aula 02

Tipos de dados variaves, operadores e comandos basicos
- Tipos de dados
  - Numerico: Numeros inteiros e reias
  - caractere: um simbolo(letra) da tabela ASCII
  - Logico: verdedeiro/falso
  - literal: agregados de caracteres (varios caracteres)
- operadores
  - Os operadores são meios pelo qual
incrementamos,decrementamos,comparamos
e avaliamos dados dentro do computador
  - tipos de operadores
    - Operadores Aritméticos: operadores aritméticos são os utilizados
para obter resultados numéricos
    - Operadores Relacionais: Os operadores relacionais realizam a comparação entre
dois operandos e resultam em valores lógicos
(verdadeiro ou falso)
    - Operadores Lógicos: Os operadores lógicos atuam sobre expressões e
também resultam em valores lógicos
"""

numero = float(input("Digite um numero: ")) #variavel numero (float) ---> variavel real
resultado = (numero%2) #terminando a variavel que da o valor de divisão (%) ---> retorna o resto da divisão
if (resultado == 0): # caso seja resultado seja zero
  print(" seu numero é par") # retorna par
else: # qualquer outro resultado que não seja 0
  print(" seu numero é impar") # retorna impar

base = float(input("digite o numero da base:")) # declarando a variavel
expoente = float(input("digite o numero do expoente:"))
resultado = float (base**expoente) # declarando a variavel de calculo (**) ---> expoenciação
print(resultado)